query ListPublishedPosts @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  posts(where: {isPublished: {eq: true}}, orderBy: [{createdAt: DESC}]) {
    id
    title
    content
    imageUrl
    createdAt
    author {
      displayName
      profilePictureUrl
    }
    tags_via_PostTag {
      name
    }
  }
}

query GetMyFavoritePosts @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  favoritePosts(where: {userId: {eq_expr: "auth.uid"}}, orderBy: [{createdAt: DESC}]) {
    post {
      id
      title
      content
      imageUrl
      author {
        displayName
      }
    }
    createdAt
  }
}

mutation CreateNewPost($title: String!, $content: String!, $imageUrl: String, $isPublished: Boolean) @auth(level: USER, insecureReason: "This operation allows authenticated users to create their own posts.") {
  post_insert(data: {
    title: $title,
    content: $content,
    imageUrl: $imageUrl,
    isPublished: $isPublished,
    authorId_expr: "auth.uid",
    createdAt_expr: "request.time",
    updatedAt_expr: "request.time"
  }) {
    id
  }
}

mutation FollowUser($followeeId: UUID!) @auth(level: USER, insecureReason: "This operation allows authenticated users to follow other users.") {
  follow_insert(data: {
    followerId_expr: "auth.uid",
    followeeId: $followeeId,
    createdAt_expr: "request.time"
  }) {
    followerId
    followeeId
  }
}